### ISSUE TITLE
Extended components

### ISSUE THREAD

**Issue by mistermantas** [mistermantas/cstate#9]
In `v2-dev1` components are just text in an array. This needs to be addressed.

Possible layout:

```yaml
-
  name: Media Proxy
  description: This is the service responsible for serving images, audio, and video.
  partial: mediaproxy
```

Description shows **[?]** icon or **[+]** icon for more information. Should not be required.

Partial would be custom HTML (see: #7) below the component. This way, uptime metrics could be added with 3rd party JS:

![image](https://user-images.githubusercontent.com/11616378/42408985-01fb2324-81dc-11e8-979b-b48bf78d404d.png)

If there are any other possible meta tags, please reply to this issue with suggestions.
